[package]
name = "freqfs"
version = "0.5.2"
authors = ["haydn@tinychain.net"]
edition = "2018"
license = "Apache-2.0"
description = "An in-memory filesystem cache layer over tokio::fs, with LFU eviction"
repository = "https://github.com/haydnv/freqfs"
readme = "README.md"

categories = ["caching", "filesystem", "memory-management"]
keywords = ["file", "io", "cache"]

[[example]]
name = "example"

[dependencies]
async-trait = "0.1"
freqache = "~0.4.1"
futures = "0.3"
log = "0.4"
safecast = "~0.1.2"
tokio = { version = "1.21", features = ["fs", "io-util", "rt-multi-thread", "sync"] }

[dev-dependencies]
rand = "0.8"
tokio = { version = "1.21", features = ["macros", "time"] }
