[package]
name = "freqfs"
version = "0.8.0"
authors = ["code@tinychain.net"]
edition = "2021"
license = "Apache-2.0"
description = "An in-memory filesystem cache layer over tokio::fs, with LFU eviction"
repository = "https://github.com/haydnv/freqfs"
readme = "README.md"

categories = ["caching", "filesystem", "memory-management"]
keywords = ["file", "io", "cache"]

[[example]]
name = "example"
required-features = ["stream"]

[features]
all = ["logging", "stream"]
logging = ["log"]
stream = ["bytes", "destream", "tbon", "tokio-util"]

[dependencies]
async-trait = "0.1"
bytes = { version = "1.4", optional = true }
destream = { path = "../destream", optional = true }
ds-ext = { path = "../ds-ext" }
futures = "0.3"
log = { version = "0.4", optional = true }
safecast = { path = "../safecast" }
tbon = { path = "../tbon", features = ["tokio-io"], optional = true }
tokio = { version = "1.25", features = ["fs", "io-util", "rt-multi-thread", "sync", "time"] }
tokio-util = { version = "0.7", features = ["io"], optional = true }
uuid = { version = "1.3", features = ["v4"] }

[dev-dependencies]
rand = "0.8"
tokio = { version = "1.25", features = ["macros"] }
